//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OpenGL.rc
//
#define IDS_OPENGLINFO                  1
#define IDS_PRINTERGDI_ERROR            2
#define IDS_OGL_HARDWARE                3
#define IDS_OGL_HWPARTIAL               4
#define IDS_OGL_SOFTWARE                5
#define IDS_NOTAVAILABLE                6
#define IDS_ERR_MAXZOOM                 7
#define IDS_LINKMAUS_DBLKLIK            8
#define IDS_LINKMAUS_KLIK               9
#define IDS_LINKMAUS_KLIKHALT           10
#define IDS_EIGEN_AKTUEL                11
#define IDS_EIGEN_ALLES                 12
#define IDS_REOPEN_NONE                 13
#define IDS_REOPEN_FIRST                14
#define IDS_GRAFPREC_1BYTE              15
#define IDS_GRAFPREC_2BYTE              16
#define IDS_GRAFPREC_4BYTE              17
#define IDS_GRAFPREC_8BYTE              18
#define IDS_ERR_PRINTERFNC              19
#define IDS_ERR_PRINTNOMEM              20
#define IDS_ERR_PRINTNOSTART            21
#define IDS_ERR_OSNOMEM                 22
#define IDS_ERR_PATHNOTFOUND            23
#define IDS_ERR_FILENOTFOUND            24
#define IDS_ERR_EXECORRUPT              25
#define IDS_ERR_NOACCESS                26
#define IDS_ERR_BADLINK                 27
#define IDS_ERR_DDEBUSY                 28
#define IDS_ERR_DDEFAIL                 29
#define IDS_ERR_DDETIMEOUT              30
#define IDS_DLLNOTFOUND                 31
#define IDS_ERR_NOASSOC                 32
#define IDS_ERR_MEMLOW                  33
#define IDS_ERR_SHARING                 34
#define IDS_ERR_UNKNOWN                 35
#define IDS_ERR_HYPERLINK               36
#define IDS_ERR_DIMMISMATCH             37
#define IDS_ERR_DIMMULT                 38
#define IDS_ERR_DIMHCAT                 39
#define IDS_ERR_DIMVCAT                 40
#define IDS_ERR_2INDEXBAD               41
#define IDS_ERR_ROWINDEX                42
#define IDS_ERR_COLINDEX                43
#define IDS_ERR_BADMATSIZE              44
#define IDS_INTEGER_LESS                10001
#define IDS_INTEGER_LESS_EQUAL          10002
#define IDS_INTEGER_GREATER             10003
#define IDS_INTEGER_GREATER_EQUAL       10004
#define IDS_INTEGER_GREATER_LESS        10005
#define IDS_INTEGER_GREATER_EQUAL_LESS  10006
#define IDS_INTEGER_GREATER_LESS_EQUAL  10007
#define IDS_INTEGER_NOT_EQUAL           10008
#define IDS_INTEGER_LESS_GREATER        10009
#define IDS_INTEGER_LESS_GREATER_EQUAL  10010
#define IDS_INTEGER_LESS_EQUAL_GREATER  10011
#define IDS_INTEGER_LESS_EQUAL_GREATER_EQUAL 10012
#define IDS_NUMBER_LESS                 10013
#define IDS_NUMBER_LESS_EQUAL           10014
#define IDS_NUMBER_GREATER              10015
#define IDS_NUMBER_GREATER_EQUAL        10016
#define IDS_NUMBER_GREATER_LESS         10017
#define IDS_NUMBER_GREATER_EQUAL_LESS   10018
#define IDS_NUMBER_GREATER_LESS_EQUAL   10019
#define IDS_NUMBER_NOT_EQUAL            10020
#define IDS_NUMBER_LESS_GREATER         10021
#define IDS_NUMBER_LESS_GREATER_EQUAL   10022
#define IDS_NUMBER_LESS_EQUAL_GREATER   10023
#define IDS_NUMBER_LESS_EQUAL_GREATER_EQUAL 10024
#define IDD_DLG_OPENGL_INFO             10131
#define IDD_DLG_FILE_PRINT_OPTIONS      10132
#define IDD_DLG_OPTIONS                 10133
#define IDC_CURROTATE                   10133
#define IDC_STATIC_VERSION              11000
#define IDC_STATIC_COPYRIGHT            11001
#define IDC_STATIC_URL                  11002
#define IDC_STATIC_ICON                 11003
#define IDC_STATIC_GL_VENDOR            11004
#define IDC_STATIC_GL_RENDERER          11005
#define IDC_STATIC_GL_VERSION           11006
#define IDC_STATIC_GL_ACCELERATION      11007
#define IDC_EDIT_GL_EXTENSIONS          11008
#define IDC_STATIC_GLU_VERSION          11009
#define IDC_EDIT_GLU_EXTENSIONS         11010
#define IDC_DETAILS                     11011
#define IDC_PRINT_MEM                   11012
#define IDC_PRINT_MEM_STANDARD          11013
#define IDC_PRINT_VIEW                  11014
#define IDC_PRINT_DOC                   11015
#define IDC_PRINT_APP                   11016
#define IDC_PRINT_BKGND_WHITE           11017
#define IDC_STATIC_OPTIONS              11018
#define IDC_STATIC_TEXT_F_ONE           11019
#define IDC_STATIC_TEXT_F_TWO           11020
#define IDC_BUTTON_HELP                 11021
#define IDC_BUTTON_PRINTER              11022
#define IDC_RADIO_MOUSE_POLICY_0        11023
#define IDC_RADIO_MOUSE_POLICY_1        11024
#define IDC_RADIO_MOUSE_POLICY_2        11025
#define IDC_CHECK_PROP_POLICY           11026
#define IDC_CHECK_REOPEN_POLICY         11027
#define IDC_RADIO_SERIALZE_GRAPH_BYTES_1 11028
#define IDC_RADIO_SERIALZE_GRAPH_BYTES_2 11029
#define IDC_RADIO_SERIALZE_GRAPH_BYTES_4 11030
#define IDC_RADIO_SERIALZE_GRAPH_BYTES_8 11031
#define IDC_STATIC_SERIALZE_GRAPH_BYTES_GBOX 11032
#define ID_HELP_CONTENTS                42770
#define ID_HELP_OPENGL_INFO             42771
#define ID_FILE_PRINT_EX                42772
#define ID_FILE_PRINT_PREVIEW_EX        42773
#define ID_FILE_PRINT_SETUP_EX          42774
#define ID_CHANGE_POLICY                42775
#define ID_CHANGE_MOUSE_POLICY          42776
#define ID_CHANGE_PROP_POLICY           42777
#define ID_CHANGE_REOPEN_POLICY         42778
#define ID_OPTIONS_FONT                 42779
#define ID_SERIALIZE_GRAPH_ONE_BYTE     42780
#define ID_SERIALIZE_GRAPH_TWO_BYTE     42781
#define ID_SERIALIZE_GRAPH_FOUR_BYTE    42782
#define ID_SERIALIZE_GRAPH_EIGHT_BYTE   42783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10134
#define _APS_NEXT_COMMAND_VALUE         42784
#define _APS_NEXT_CONTROL_VALUE         11036
#define _APS_NEXT_SYMED_VALUE           10025
#endif
#endif
